/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SystemRouteImport } from './routes/system'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBatchesRouteImport } from './routes/_authenticated/batches'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedDispatchesRouteImport } from './routes/_authenticated/dispatches'
import { Route as AuthenticatedFarmersRouteImport } from './routes/_authenticated/farmers'
import { Route as AuthenticatedFarmsRouteImport } from './routes/_authenticated/farms'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedPricesRouteImport } from './routes/_authenticated/prices'
import { Route as AuthenticatedQcRouteImport } from './routes/_authenticated/qc'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedRecallRouteImport } from './routes/_authenticated/recall'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedTourRouteImport } from './routes/_authenticated/tour'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVisitsRouteImport } from './routes/_authenticated/visits'
import { Route as AuthenticatedWaterRouteImport } from './routes/_authenticated/water'
import { Route as TraceCodeRouteImport } from './routes/trace.$code'
import { Route as AuthenticatedBatchesBatchIdRouteImport } from './routes/_authenticated/batches_.$batchId'
import { Route as AuthenticatedContractsContractIdRouteImport } from './routes/_authenticated/contracts_.$contractId'
import { Route as AuthenticatedFarmersFarmerIdRouteImport } from './routes/_authenticated/farmers_.$farmerId'
import { Route as AuthenticatedFarmsFarmIdRouteImport } from './routes/_authenticated/farms_.$farmId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBatchesRoute = AuthenticatedBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDispatchesRoute = AuthenticatedDispatchesRouteImport.update({
  id: '/dispatches',
  path: '/dispatches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFarmersRoute = AuthenticatedFarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFarmsRoute = AuthenticatedFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricesRoute = AuthenticatedPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQcRoute = AuthenticatedQcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecallRoute = AuthenticatedRecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTourRoute = AuthenticatedTourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitsRoute = AuthenticatedVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWaterRoute = AuthenticatedWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TraceCodeRoute = TraceCodeRouteImport.update({
  id: '/trace/$code',
  path: '/trace/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBatchesBatchIdRoute =
  AuthenticatedBatchesBatchIdRouteImport.update({
    id: '/batches_/$batchId',
    path: '/batches/$batchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsContractIdRoute =
  AuthenticatedContractsContractIdRouteImport.update({
    id: '/contracts_/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFarmersFarmerIdRoute =
  AuthenticatedFarmersFarmerIdRouteImport.update({
    id: '/farmers_/$farmerId',
    path: '/farmers/$farmerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFarmsFarmIdRoute =
  AuthenticatedFarmsFarmIdRouteImport.update({
    id: '/farms_/$farmId',
    path: '/farms/$farmId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/ask': typeof AuthenticatedAskRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/dispatches': typeof AuthenticatedDispatchesRoute
  '/farmers': typeof AuthenticatedFarmersRoute
  '/farms': typeof AuthenticatedFarmsRoute
  '/map': typeof AuthenticatedMapRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/qc': typeof AuthenticatedQcRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/recall': typeof AuthenticatedRecallRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/tour': typeof AuthenticatedTourRoute
  '/users': typeof AuthenticatedUsersRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/water': typeof AuthenticatedWaterRoute
  '/trace/$code': typeof TraceCodeRoute
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/farms/$farmId': typeof AuthenticatedFarmsFarmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/ask': typeof AuthenticatedAskRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/dispatches': typeof AuthenticatedDispatchesRoute
  '/farmers': typeof AuthenticatedFarmersRoute
  '/farms': typeof AuthenticatedFarmsRoute
  '/map': typeof AuthenticatedMapRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/qc': typeof AuthenticatedQcRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/recall': typeof AuthenticatedRecallRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/tour': typeof AuthenticatedTourRoute
  '/users': typeof AuthenticatedUsersRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/water': typeof AuthenticatedWaterRoute
  '/trace/$code': typeof TraceCodeRoute
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/farms/$farmId': typeof AuthenticatedFarmsFarmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/batches': typeof AuthenticatedBatchesRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRoute
  '/_authenticated/dispatches': typeof AuthenticatedDispatchesRoute
  '/_authenticated/farmers': typeof AuthenticatedFarmersRoute
  '/_authenticated/farms': typeof AuthenticatedFarmsRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/prices': typeof AuthenticatedPricesRoute
  '/_authenticated/qc': typeof AuthenticatedQcRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/recall': typeof AuthenticatedRecallRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/tour': typeof AuthenticatedTourRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/visits': typeof AuthenticatedVisitsRoute
  '/_authenticated/water': typeof AuthenticatedWaterRoute
  '/trace/$code': typeof TraceCodeRoute
  '/_authenticated/batches_/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/_authenticated/contracts_/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/_authenticated/farmers_/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/_authenticated/farms_/$farmId': typeof AuthenticatedFarmsFarmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/system'
    | '/alerts'
    | '/ask'
    | '/audit'
    | '/batches'
    | '/compliance'
    | '/contracts'
    | '/dashboard'
    | '/deliveries'
    | '/demo'
    | '/dispatches'
    | '/farmers'
    | '/farms'
    | '/map'
    | '/prices'
    | '/qc'
    | '/ranking'
    | '/recall'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/tour'
    | '/users'
    | '/visits'
    | '/water'
    | '/trace/$code'
    | '/batches/$batchId'
    | '/contracts/$contractId'
    | '/farmers/$farmerId'
    | '/farms/$farmId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/system'
    | '/alerts'
    | '/ask'
    | '/audit'
    | '/batches'
    | '/compliance'
    | '/contracts'
    | '/dashboard'
    | '/deliveries'
    | '/demo'
    | '/dispatches'
    | '/farmers'
    | '/farms'
    | '/map'
    | '/prices'
    | '/qc'
    | '/ranking'
    | '/recall'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/tour'
    | '/users'
    | '/visits'
    | '/water'
    | '/trace/$code'
    | '/batches/$batchId'
    | '/contracts/$contractId'
    | '/farmers/$farmerId'
    | '/farms/$farmId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/system'
    | '/_authenticated/alerts'
    | '/_authenticated/ask'
    | '/_authenticated/audit'
    | '/_authenticated/batches'
    | '/_authenticated/compliance'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/deliveries'
    | '/_authenticated/demo'
    | '/_authenticated/dispatches'
    | '/_authenticated/farmers'
    | '/_authenticated/farms'
    | '/_authenticated/map'
    | '/_authenticated/prices'
    | '/_authenticated/qc'
    | '/_authenticated/ranking'
    | '/_authenticated/recall'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/stock'
    | '/_authenticated/tour'
    | '/_authenticated/users'
    | '/_authenticated/visits'
    | '/_authenticated/water'
    | '/trace/$code'
    | '/_authenticated/batches_/$batchId'
    | '/_authenticated/contracts_/$contractId'
    | '/_authenticated/farmers_/$farmerId'
    | '/_authenticated/farms_/$farmId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SystemRoute: typeof SystemRoute
  TraceCodeRoute: typeof TraceCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/batches': {
      id: '/_authenticated/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthenticatedBatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatches': {
      id: '/_authenticated/dispatches'
      path: '/dispatches'
      fullPath: '/dispatches'
      preLoaderRoute: typeof AuthenticatedDispatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farmers': {
      id: '/_authenticated/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof AuthenticatedFarmersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farms': {
      id: '/_authenticated/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof AuthenticatedFarmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prices': {
      id: '/_authenticated/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AuthenticatedPricesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qc': {
      id: '/_authenticated/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof AuthenticatedQcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recall': {
      id: '/_authenticated/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof AuthenticatedRecallRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tour': {
      id: '/_authenticated/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof AuthenticatedTourRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visits': {
      id: '/_authenticated/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AuthenticatedVisitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/water': {
      id: '/_authenticated/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof AuthenticatedWaterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/trace/$code': {
      id: '/trace/$code'
      path: '/trace/$code'
      fullPath: '/trace/$code'
      preLoaderRoute: typeof TraceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/batches_/$batchId': {
      id: '/_authenticated/batches_/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof AuthenticatedBatchesBatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts_/$contractId': {
      id: '/_authenticated/contracts_/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farmers_/$farmerId': {
      id: '/_authenticated/farmers_/$farmerId'
      path: '/farmers/$farmerId'
      fullPath: '/farmers/$farmerId'
      preLoaderRoute: typeof AuthenticatedFarmersFarmerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farms_/$farmId': {
      id: '/_authenticated/farms_/$farmId'
      path: '/farms/$farmId'
      fullPath: '/farms/$farmId'
      preLoaderRoute: typeof AuthenticatedFarmsFarmIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBatchesRoute: typeof AuthenticatedBatchesRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRoute
  AuthenticatedDispatchesRoute: typeof AuthenticatedDispatchesRoute
  AuthenticatedFarmersRoute: typeof AuthenticatedFarmersRoute
  AuthenticatedFarmsRoute: typeof AuthenticatedFarmsRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedPricesRoute: typeof AuthenticatedPricesRoute
  AuthenticatedQcRoute: typeof AuthenticatedQcRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRecallRoute: typeof AuthenticatedRecallRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTourRoute: typeof AuthenticatedTourRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVisitsRoute: typeof AuthenticatedVisitsRoute
  AuthenticatedWaterRoute: typeof AuthenticatedWaterRoute
  AuthenticatedBatchesBatchIdRoute: typeof AuthenticatedBatchesBatchIdRoute
  AuthenticatedContractsContractIdRoute: typeof AuthenticatedContractsContractIdRoute
  AuthenticatedFarmersFarmerIdRoute: typeof AuthenticatedFarmersFarmerIdRoute
  AuthenticatedFarmsFarmIdRoute: typeof AuthenticatedFarmsFarmIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBatchesRoute: AuthenticatedBatchesRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedDemoRoute: AuthenticatedDemoRoute,
  AuthenticatedDispatchesRoute: AuthenticatedDispatchesRoute,
  AuthenticatedFarmersRoute: AuthenticatedFarmersRoute,
  AuthenticatedFarmsRoute: AuthenticatedFarmsRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedPricesRoute: AuthenticatedPricesRoute,
  AuthenticatedQcRoute: AuthenticatedQcRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRecallRoute: AuthenticatedRecallRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTourRoute: AuthenticatedTourRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVisitsRoute: AuthenticatedVisitsRoute,
  AuthenticatedWaterRoute: AuthenticatedWaterRoute,
  AuthenticatedBatchesBatchIdRoute: AuthenticatedBatchesBatchIdRoute,
  AuthenticatedContractsContractIdRoute: AuthenticatedContractsContractIdRoute,
  AuthenticatedFarmersFarmerIdRoute: AuthenticatedFarmersFarmerIdRoute,
  AuthenticatedFarmsFarmIdRoute: AuthenticatedFarmsFarmIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SystemRoute: SystemRoute,
  TraceCodeRoute: TraceCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
